name: coordinator
version: '1.3'
main: net.zapp.coordinator.Coordinator
api-version: '1.20'
author: "Mirroray41"

softdepend: [PlaceholderAPI]

commands:
  cr:
    description: "opens coordinator config menu"
    #has reload sub command requiring "cr.reload" permission!
permissions:
  cr.use:
    default: true
  cr.reload:
    op: true