name: coordinator
version: '1.6.1'
main: net.zapp.coordinator.Coordinator
api-version: '1.13'
author: "Mirroray41"

softdepend: [PlaceholderAPI]

commands:
  cr:
    description: "opens coordinator config menu"

permissions:
  cr.use:
    default: true
  cr.reload:
    op: true
  cr.set:
    op: true
  cr.get:
    op: true